# TP sur la génération des matrices élémentaires

I . Nous proposons dans le code qui suit une construction progressive d'une focntion qui se permet de décomposer une matrice de taille nxn en Diagonale D, Triangulaire supérieur U et, en triangulaire inférieur L. Nous tenons aussi à préciser que puisque nous ne traitons ici que les systèmes linéaires, nos matrices seront dites matrices carrées (n x n).

In [3]:
import numpy as np

In [14]:
def decompositionLDU(A):
    A=np.array(A)
    n=len(A)
    if len(A[0])!=n:
        raise Exception('La matrice n`est pas n x n')    
    print(">>>>>>>>>>La matrice A de dimension " + str(n) + " est :" )
    print(A)
    

In [15]:
A=([[3,1,2],[1,2,3],[2,3,1]])
decompositionLDU(A)
%timeit() 

>>>>>>>>>>La matrice A de dimension 3 est :
[[3 1 2]
 [1 2 3]
 [2 3 1]]
10000000 loops, best of 3: 19.6 ns per loop


***************************************************************
Nous savons que A = L+D+U, trouvons la matrice Diagonale D de A :
***************************************************************

In [16]:
def decompositionLDU(A):
    A=np.array(A)
    n=len(A)
    if len(A[0])!=n:
        raise Exception('La matrice n`est pas n x n') 
    print(">>>>>>>>>>La matrice A de dimension " + str(n) + " est :" )
    print(A)
    D=A*np.eye(n)
    D=np.array(D)
    print(">>>>>>>>>>La matrice Diagonale D est : ")
    print(D)


In [17]:
A=([[3,1,2],[1,2,3],[2,3,1]])
decompositionLDU(A)
%timeit() 

>>>>>>>>>>La matrice A de dimension 3 est :
[[3 1 2]
 [1 2 3]
 [2 3 1]]
>>>>>>>>>>La matrice Diagonale D est : 
[[ 3.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  1.]]
10000000 loops, best of 3: 19.4 ns per loop


*****************
Maintenons nous pouvons trouver la matricie triangulaire inférieur L de A en partant de D:
**********

In [18]:
def decompositionLDU(A):
    A=np.array(A)
    n=len(A)
    if len(A[0])!=n:
        raise Exception('La matrice n`est pas n x n') 
    print(">>>>>>>>>>La matrice A de dimension " + str(n) + " est :" )
    print(A)
    D=A*np.eye(n)
    D=np.array(D)
    print(">>>>>>>>>>La matrice Diagonale D est : ")
    print(D)    
    L=np.tril(A)-D
    print(">>>>>>>>>>La matrice Triangulaire inférieur L est : ")
    print(L)


In [19]:
A=([[3,1,2],[1,2,3],[2,3,1]])
decompositionLDU(A)
%timeit() 

>>>>>>>>>>La matrice A de dimension 3 est :
[[3 1 2]
 [1 2 3]
 [2 3 1]]
>>>>>>>>>>La matrice Diagonale D est : 
[[ 3.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  1.]]
>>>>>>>>>>La matrice Triangulaire inférieur L est : 
[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 2.  3.  0.]]
10000000 loops, best of 3: 19.6 ns per loop


******************************************************************************
Nous pouvons à présent trouver la matrice triangulaire supérieur U de 2 façons :
******************************************************************************

1) D'abord en partant de D

In [20]:
def decompositionLDU(A):
    A=np.array(A)
    n=len(A)
    if len(A[0])!=n:
        raise Exception('La matrice n`est pas n x n') 
    print(">>>>>>>>>>La matrice A de dimension " + str(n) + " est :" )
    print(A)
    D=A*np.eye(n)
    D=np.array(D)
    print(">>>>>>>>>>La matrice Diagonale D est : ")
    print(D)    
    L=np.tril(A)-D
    print(">>>>>>>>>>La matrice Triangulaire inférieur L est : ")
    print(L)
    U=np.triu(A)-D
    print(">>>>>>>>>>La matrice Triangulaire supérieur U est : ")
    print(U)

In [21]:
A=([[3,1,2],[1,2,3],[2,3,1]])
decompositionLDU(A)
%timeit() 

>>>>>>>>>>La matrice A de dimension 3 est :
[[3 1 2]
 [1 2 3]
 [2 3 1]]
>>>>>>>>>>La matrice Diagonale D est : 
[[ 3.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  1.]]
>>>>>>>>>>La matrice Triangulaire inférieur L est : 
[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 2.  3.  0.]]
>>>>>>>>>>La matrice Triangulaire supérieur U est : 
[[ 0.  1.  2.]
 [ 0.  0.  3.]
 [ 0.  0.  0.]]
The slowest run took 62.15 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 19.8 ns per loop


2) Ensuite en Tirant D de la formulee générale A=L+D+U

In [22]:
def decompositionLDU(A):
    A=np.array(A)
    n=len(A)
    if len(A[0])!=n:
        raise Exception('La matrice n`est pas n x n') 
    print(">>>>>>>>>>La matrice A de dimension " + str(n) + " est :" )
    print(A)
    D=A*np.eye(n)
    D=np.array(D)
    print(">>>>>>>>>>La matrice Diagonale D est : ")
    print(D)    
    L=np.tril(A)-D
    print(">>>>>>>>>>La matrice Triangulaire inférieur L est : ")
    print(L)
    U=A-D-L
    print(">>>>>>>>>>La matrice Triangulaire supérieur U est : ")
    print(U)

In [23]:
A=([[3,1,2],[1,2,3],[2,3,1]])
decompositionLDU(A)
%timeit() 

>>>>>>>>>>La matrice A de dimension 3 est :
[[3 1 2]
 [1 2 3]
 [2 3 1]]
>>>>>>>>>>La matrice Diagonale D est : 
[[ 3.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  1.]]
>>>>>>>>>>La matrice Triangulaire inférieur L est : 
[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 2.  3.  0.]]
>>>>>>>>>>La matrice Triangulaire supérieur U est : 
[[ 0.  1.  2.]
 [ 0.  0.  3.]
 [ 0.  0.  0.]]
10000000 loops, best of 3: 18.7 ns per loop


Nous pouvons ainsi constater que trouver U à partir de la formule générale semble plus rapide d'un 0.7 ns près.
*******

**********
PREUVE:
Afin de démontrer que toutes les conditions de décompositions LDU sont réunies, nous nous permettons ici de d'afficher et de compare le résultat L+D+U à A

In [24]:
def decompositionLDU(A):
    A=np.array(A)
    n=len(A)
    if len(A[0])!=n:
        raise Exception('La matrice n`est pas n x n') 
    print(">>>>>>>>>>La matrice A de dimension " + str(n) + " est :" )
    print(A)
    D=A*np.eye(n)
    D=np.array(D)
    print(">>>>>>>>>>La matrice Diagonale D est : ")
    print(D)    
    L=np.tril(A)-D
    print(">>>>>>>>>>La matrice Triangulaire inférieur L est : ")
    print(L)
    U=np.triu(A)-D
    print(">>>>>>>>>>La matrice Triangulaire supérieur U est : ")
    print(U)
    B=L+D+U
    if (B==A).all() :
        
        print(">>>>>>>>>>>>>>>>>>>>>>>>>>La décomposition de A a été efectué avec succès!<<<<<<<<<<<<<<<<<<<<<<<")
    else:
        print("Echec de décomposition")

In [25]:
A=([[3,1,2],[1,2,3],[2,3,1]])
decompositionLDU(A)
%timeit() 

>>>>>>>>>>La matrice A de dimension 3 est :
[[3 1 2]
 [1 2 3]
 [2 3 1]]
>>>>>>>>>>La matrice Diagonale D est : 
[[ 3.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  1.]]
>>>>>>>>>>La matrice Triangulaire inférieur L est : 
[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 2.  3.  0.]]
>>>>>>>>>>La matrice Triangulaire supérieur U est : 
[[ 0.  1.  2.]
 [ 0.  0.  3.]
 [ 0.  0.  0.]]
>>>>>>>>>>>>>>>>>>>>>>>>>>La décomposition de A a été efectué avec succès!<<<<<<<<<<<<<<<<<<<<<<<
10000000 loops, best of 3: 19.9 ns per loop


**************
II. Produit matricielle : ci-dessous, une fonction prodmat qui se propose de calculer manuellement le produit matriciel  de deux matrice et prodmatdot avec la méthode dot

In [26]:
def prodmat(A,B):
    A=np.array(A)
    B=np.array(B)
    if len(A[0])!=len(A):
        raise Exception('La matrice A n`est pas n x n') 
    if len(B[0])!=len(B):
        raise Exception('La matrice n`est pas n x n') 
    print(">>>>>>>>>>La première matrice est est : ")
    print(A)
    print(">>>>>>>>>>La seconde matrice est est : ")
    print(B)
    P=A@B
    print(">>>>>>>>>>Le produit matriciel A * B est : ")
    print(P)

In [27]:
A=([[1,2],[0,3]])
B=([[7,4],[2,3]])
prodmat(A,B)
%timeit()

>>>>>>>>>>La première matrice est est : 
[[1 2]
 [0 3]]
>>>>>>>>>>La seconde matrice est est : 
[[7 4]
 [2 3]]
>>>>>>>>>>Le produit matriciel A * B est : 
[[11 10]
 [ 6  9]]
The slowest run took 63.80 times longer than the fastest. This could mean that an intermediate result is being cached.
100000000 loops, best of 3: 19.3 ns per loop


In [28]:
def prodmatdot(A,B):
    A=np.array(A)
    B=np.array(B)  
    if len(A[0])!=len(A):
        raise Exception('La matrice A n`est pas n x n') 
    if len(B[0])!=len(B):
        raise Exception('La matrice n`est pas n x n')
    print(">>>>>>>>>>La première matrice est est : ")
    print(A)
    print(">>>>>>>>>>La seconde matrice est est : ")
    print(B)
    P=np.dot(A,B)
    print(">>>>>>>>>>Le produit matriciel A * B avec la méthode dot est : ")
    print(P)

In [29]:
A=([[1,2],[0,3]])
B=([[7,4],[2,3]])
prodmatdot(A,B)
%timeit()

>>>>>>>>>>La première matrice est est : 
[[1 2]
 [0 3]]
>>>>>>>>>>La seconde matrice est est : 
[[7 4]
 [2 3]]
>>>>>>>>>>Le produit matriciel A * B avec la méthode dot est : 
[[11 10]
 [ 6  9]]
100000000 loops, best of 3: 19.2 ns per loop


*************
Conclusion : Alors que la méthode DOT ne prend que 18.7 ns de temps d'execution, le produit matriciel manuel met plus de temps soit 19 ns
*******************

*********************************
III. Matrice de permutation : La matrice T[i,j] permettant la permutation des lignes i et j 

In [30]:
def T(n,i,j):
    if i>=n or j>=n or i<0 or j<0:
        raise Exception('La matrice n`est pas n x n')
    T = np.eye(n)
    T[[j,i]]=T[[i,j]]
    return T

In [31]:
tab=T(3,2,1)
print(tab)
%timeit()

[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
100000000 loops, best of 3: 18.9 ns per loop


*************
IV. Matrice  permettant la multiplication de la ligne i par λ !

In [32]:
def Di(A,i,λ):
    D=np.array(A)     
    n=len(D)
    print('La matrice de départ est :')
    print(D)    
    if len(D[0])!=n:
        raise Exception('La matrice A n`est pas n x n')
    j=0
    while(j<n):
        v=D[i,j]*λ
        D[i,j]=v
        j+=1
    print('La matrice D est :')
    return D 

In [33]:
A=([[3,1,2],[1,2,3],[2,3,1]])
i=1
λ=4
tabDi=Di(A,i,λ)
print(tabDi)

La matrice de départ est :
[[3 1 2]
 [1 2 3]
 [2 3 1]]
La matrice D est :
[[ 3  1  2]
 [ 4  8 12]
 [ 2  3  1]]


****************
V. Matrice  permettant d'ajouter à la ligne r, λ fois la ligne  s

In [34]:
def Lrs(n,r,s,λ):
    if r>=n or s>=n:
        raise Exception('Uncompatible dimension')
    L=np.eye(n)
    L[r,s]=λ
    return L

In [35]:
n=3
r=2
s=0
λ=4
tabLrs=Lrs(n,r,s,λ)
print(tabLrs)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 4.  0.  1.]]


In [36]:
a = Lrs(3,1,1,4)@Lrs(3,2,2,4)
print(a)

[[ 1.  0.  0.]
 [ 0.  4.  0.]
 [ 0.  0.  4.]]


***************************
VI. Les Matrice inverses de T, D et L

In [37]:
invT=np.linalg.inv(tab)
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>l`inverse de T est : ")
print(invT)
invDi=np.linalg.inv(tabDi)
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>l`inverse de Di(λ) est : ")
print(invDi)
invLrs=np.linalg.inv(tabLrs)
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>l`inverse de Lrs est : ")
print(invLrs)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>l`inverse de T est : 
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>l`inverse de Di(λ) est : 
[[ 0.38888889 -0.06944444  0.05555556]
 [-0.27777778  0.01388889  0.38888889]
 [ 0.05555556  0.09722222 -0.27777778]]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>l`inverse de Lrs est : 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-4.  0.  1.]]


VII. La matrice M et son inverse

In [4]:
def M(n,i,l):
    if len(l) != n-1-i or i>=n-1 or i<0:
        raise Exception('Uncompatible dimension')
    A = np.eye(n)
    A[i+1:,i]=l
    return A

In [5]:
l=[-1/3,-2/3] #liste de valeur qu'on veut insérer dans notre matrice M
#cas de l'exercice vu au cours avec Gauss
print("la matrice M avec des valeurs donnée manuellement est :")
tabM=M(3,0,l)
print(tabM)

la matrice M avec des valeurs donnée manuellement est :
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-0.66666667  0.          1.        ]]


In [40]:
invM=np.linalg.inv(M(3,0,l))
print("la matrice inverse de M avec des valeurs donnée manuellement est :")
print(invM)

la matrice inverse de M avec des valeurs donnée manuellement est :
[[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.66666667  0.          1.        ]]


Le produit matriciel entre la matrice M et son inverse invM = matrice identité :

In [41]:
print(invM@tabM)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
